# Namespace dedicado para la aplicación de prueba
apiVersion: v1
kind: Namespace
metadata:
  name: test-environment
  labels:
    name: test-environment
    purpose: testing

---
# Deployment de aplicación de prueba
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: test-environment
  labels:
    app: test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: ENVIRONMENT
          value: "test"
        volumeMounts:
        - name: nginx-config
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: nginx-config
        configMap:
          name: test-app-config

---
# ConfigMap con contenido personalizado
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-app-config
  namespace: test-environment
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>MicroK8s Test App</title>
        <style>
            body { 
                font-family: Arial, sans-serif; 
                text-align: center; 
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                margin: 0;
                padding: 50px;
            }
            .container {
                background: rgba(255,255,255,0.1);
                padding: 30px;
                border-radius: 10px;
                display: inline-block;
            }
            h1 { color: #fff; }
            .info { margin: 20px 0; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 MicroK8s Test Application</h1>
            <div class="info">
                <p><strong>Status:</strong> Running successfully!</p>
                <p><strong>Environment:</strong> Test</p>
                <p><strong>Timestamp:</strong> <span id="timestamp"></span></p>
            </div>
        </div>
        <script>
            document.getElementById('timestamp').textContent = new Date().toLocaleString();
        </script>
    </body>
    </html>

---
# Service para exponer la aplicación
apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  namespace: test-environment
  labels:
    app: test-app
spec:
  selector:
    app: test-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  type: ClusterIP

---
# Service LoadBalancer para acceso externo
apiVersion: v1
kind: Service
metadata:
  name: test-app-loadbalancer
  namespace: test-environment
  labels:
    app: test-app
  annotations:
    metallb.universe.tf/address-pool: default-addresspool
spec:
  selector:
    app: test-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  type: LoadBalancer

---
# Service NodePort para acceso externo (alternativa)
apiVersion: v1
kind: Service
metadata:
  name: test-app-nodeport
  namespace: default
  labels:
    app: test-app
spec:
  selector:
    app: test-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
    name: http
  type: NodePort
