apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    # Instalado en VM lubuntu-tools mediante
    # https://github.com/perfeccion-ar/infraestructura-clasica-y-avanzada/wiki/NFS
    server: 10.10.151.5
    path: /srv/nfs
